version: 2
registries:
  dockerhub:
      type: docker-registry
      url: registry.hub.docker.com
      username: mouismail
      password: ${{secrets.DOCKERHUB_PASSWORD}}
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    assignees:
      - mouismail
    labels:
      - "dependabot"
      - "gomod"
      - "dependencies"
    commit-message:
      prefix: "[go.mod/go.sum]"
    ignore:
    - dependency-name: "github.com/go-git/go-git/v5"
      versions: ["5.x"]
