name: Reusable Workflow with Matrix Exclusions

on:
  workflow_call:
    inputs:
      exclude-matrix:
        description: 'Matrix exclusions in JSON format'
        required: false
        type: string
        default: '{}'

jobs:
  example-job:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [18.04, 20.04, 2016, 2019, 10.15, 11]
        exclude: ${{ fromJSON(inputs.exclude-matrix) }}  # Exclude now properly part of the matrix
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Run a script
        run: echo "Running on ${{ matrix.os }} version ${{ matrix.version }}"
